name: 👨‍🔧 Renovate

on:
  workflow_dispatch:
  schedule:
    - timezone: Europe/Warsaw
      cron: "0 0,2,4 * * 1-5"

jobs:
  renovate:
    uses: cdqag/renovate/.github/workflows/run.yaml@v1
    secrets: inherit
